// Section variations for mock data generation
export const sectionVariations = [
  'Coverage Summary',
  'Policy Information', 
  'Coverage Details',
  'Policy Holder',
  'Special Provisions',
  'Additional Insureds',
  'Certificate Information',
  'Producer',
  'Description',
  'Deductibles',
  'Endorsement Information',
  'Premium Information',
  'Coverage Enhancements',
  'Limitations',
  'Form Information',
  'Named Insureds',
  'Aggregate Limits',
  'Property Coverage',
  'Coverage Scope',
  'Period Information',
  'Workers Compensation',
  'Vehicle Information',
  'Driver Information',
  'Usage Classification',
  'Territory Information',
  'Additional Coverages'
];